{% set major_minor = "2.24" %}
{% set version = major_minor + ".33" %}

package:
  name: gtk2
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/GNOME/sources/gtk+/{{ major_minor }}/gtk+-{{ version }}.tar.xz
  sha256: ac2ac757f5942d318a311a54b0c80b5ef295f299c2a73c632f6bfb1ff49cc6da

build:
  number: 2
  skip: True   # [win]
  skip: True   # [s390x]
  ignore_run_exports:
    - atk
  missing_dso_whitelist:
    - "*/libc.*so*"
    - "*/libm.*so*"
    - "*/libpthread.*so*"

requirements:
  build:
    - make
    - pkg-config
    - perl
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}        # [linux]
    - {{ cdt('libxau-devel') }}        # [linux]
    - {{ cdt('libxext-devel') }}       # [linux]
    - {{ cdt('libxrender-devel') }}    # [linux]
    - {{ cdt('libxcb') }}              # [linux]
  host:
    - atk
    - cairo
    - fontconfig
    - freetype
    - harfbuzz
    - gdk-pixbuf
    - glib
    - python
    - pango
  run:
    - atk
    - python
    - cairo
    - fontconfig
    - freetype
    - harfbuzz
    - gdk-pixbuf
    - glib
    - pango
test:
  commands:
    - test -f ${PREFIX}/lib/libgtk-x11-2.0{{ SHLIB_EXT }}  # [linux]
    - test -f ${PREFIX}/lib/libgtk-quartz-2.0{{ SHLIB_EXT }}  # [osx]

about:
  home: https://developer.gnome.org/gtk/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: Primary library used to construct user interfaces in GNOME applications

extra:
  recipe-maintainers:
    - jakirkham
    - pkgw
    - xhochy
