{% set major_minor = "2.24" %}
{% set version = major_minor + ".33" %}

package:
  name: gtk2
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/gtk+/{{ major_minor }}/gtk+-{{ version }}.tar.xz
  sha256: ac2ac757f5942d318a311a54b0c80b5ef295f299c2a73c632f6bfb1ff49cc6da

build:
  number: 5
  skip: true  # [win]
  missing_dso_whitelist:  # [linux]
    - "**/libc.so.6"  # [linux]
    - "**/libpthread.so.0"  # [linux]
    - "**/libdl.so.2"  # [linux]
    - "**/librt.so.1"  # [linux]
    - "**/libm.so.6"  # [linux]
    - "**/ld-linux-x86-64.so.2"  # [linux]
    - "**/ld64.so.1"  # [linux]
  ignore_run_exports:
    - pixman
    - harfbuzz  # [osx]; (quartz used on osx)
    - fontconfig  # [osx]; (quartz used on osx)
    - freetype  # [osx]; (quartz used on osx)

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - make
    - pkg-config
    - perl *
    - gnuconfig  # [unix]
    - gobject-introspection >=0.9.3
    - pthread-stubs  # [linux]
  host:
    - gobject-introspection >=0.9.3
    - atk-1.0 >=1.29.2
    - cairo {{ cairo }}
    - gdk-pixbuf 2
    - gettext  # [osx]
    - glib {{ glib }}
    - pango {{ pango }}
    - harfbuzz {{ harfbuzz }}  # [linux]; (quartz used on osx)
    - fontconfig {{ fontconfig }}  # [linux]; (quartz used on osx)
    - freetype {{ freetype }}  # [linux]; (quartz used on osx)
    - xorg-libxrender  # [linux]
    - xorg-libx11  # [linux]
    - xorg-libxext  # [linux]
  run:
    - atk-1.0 >=1.29.2
    - cairo >=1.6
    - gdk-pixbuf >=2.21.0
    - gettext  # [osx]
    - glib >=2.28.0
    - pango >=1.20
    - harfbuzz  # [linux]; (quartz used on osx)
    - fontconfig  # [linux]; (quartz used on osx)
    - freetype  # [linux]; (quartz used on osx)

test:
  commands:
    - test -f ${PREFIX}/lib/libgtk-x11-2.0{{ SHLIB_EXT }}  # [linux]
    - test -f ${PREFIX}/lib/libgtk-quartz-2.0{{ SHLIB_EXT }}  # [osx]

about:
  home: https://www.gtk.org/
  license: LGPL-2.1-or-later
  license_file: COPYING
  license_family: LGPL
  summary: Primary library used to construct user interfaces in GNOME applications.
  description: |
    GTK is a free and open-source cross-platform widget toolkit for creating graphical user interfaces.
    It is one of the most popular toolkits for the Wayland and X11 windowing systems.
  dev_url: https://gitlab.gnome.org/GNOME/gtk
  doc_url: https://developer-old.gnome.org/gtk2/stable/index.html

extra:
  recipe-maintainers:
    - jakirkham
    - pkgw
    - xhochy