travis:
  secure:
    BINSTAR_TOKEN: DkljfdrhyQvhYI6gOEXOnSQr0j8kkl33iac1JdHCPW3uKB48laXGUh7HoU/VibPrsFwXiOeMSXKG6/pC5oy2AApvOAZw+ooxL88mUO9qRn2yn08aoAnaVEbpgH4S3WAoLK3LIYfIYLCRDlHA4fTnBA26nBg8IUnozG+JOXSs6blPFD2z5uVSA3MkjcVvDXcemYoKUol1zKrLriRjs4ig82UnBMWA0vAEOtm4eu/cMC2UHJVr1137OAmYaEqKGmsYcEkM/XMQT+AkOdM9idc6AmuK8buYI53UZiwq4jhuZoAPnHFFy1FEAV5uOo8gONrBNMv5b5BaTzZZVAIX4f6H8XHnGyF0UTUrohpLff3plqXPlR6dH5w3L0iqpFBilRV7dc2BBPE9JW8HhwJN290EXis6rdEKWFzHtCHyv0kjE6QUBtCfGDA3IlPq1kem0b3N3+Bz0YMpjimDQwTiIeEQPkwbazb+YSvgNkHXWBoOcFy70yby/j9uhBFaNRl1js6GUIwg+Lz/y9VcFq+jJT2REqAz65pfH74ZYWyHACSs1ftJDrMM2vYnskZlCdl2v4kiA4VRFaKG7VEQ4HlBx6JZnXAsq+yu0y+hdeEUV3EzAWE4OOtbn+dDC+TKDwpzGmhlqzR+sjU48NIShkAbhT5gPr07Pb18w4kEo8bfp8ad7bc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
